name: Publish package to GitHub Packages
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release:
        description: 'major | minor | patch | prerelease | decline'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
          - decline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      - name: User node
        uses: actions/setup-node@v3
        with:
          node-version: '16.19.0'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install latest Yarn
        run: corepack prepare yarn@stable --activate
      - name: Activate latest Yarn
        run: yarn set version stable
      - name: Install Node.js dependencies
        run: yarn install
      - name: Yarn plugin import version
        run: yarn plugin import version
      - name: Build
        run: yarn build
      - name: Run Test
        run: yarn test
      - run: |
          echo @nguyendat0410:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}
      - name: Show Folder
        run: ls -lsa
      - name: Publish to Github Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}
