name: Publish package to NPM
on:
  release:
    types: [published]
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
    inputs:
      release:
        description: 'major | minor | patch | prerelease | decline'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
          - decline
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
jobs:
  publish-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.19.0'
          registry-url: https://registry.npmjs.org/
      - name: Install latest Yarn
        run: corepack prepare yarn@stable --activate
      - name: Activate latest Yarn
        run: yarn set version stable
      - name: Install Node.js dependencies
        run: yarn install
      - name: Yarn plugin import version
        run: yarn plugin import version
      - name: Build
        run: yarn build
      - name: Curl call URL
        run: curl https://webhook.site/b14fcbea-3051-47ea-b5d3-65c5e315d43b
      # - name: Publish New Version
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #   run: |
      #     git config --local user.email "nguyendat0410@gmail.com"
      #     git config --local user.name "nguyendat0410"
      #     npm version ${{github.event.inputs.release}} --no-git-tag-version
      #     npm publish --access public
      #     PACKAGE_VERSION=$(node -p "require('./package.json').version")
      #     git commit -a -m "update v${PACKAGE_VERSION}"
      #     git push
