name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
      - name: User node
        uses: actions/setup-node@v3
        with:
          node-version: '16.19.0'
          registry-url: 'https://npm.pkg.github.com'
      - name: Github run ci
        run: npm ci
      - name: Publish to Github Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}
